// Generated by CoffeeScript 1.6.3
(function() {
  var module;

  requirejs.config({
    baseUrl: "scripts",
    paths: {
      d3: "//cdnjs.cloudflare.com/ajax/libs/d3/3.3.9/d3.min",
      lodash: "//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.2.1/lodash.min"
    },
    shim: {
      d3: {
        exports: 'd3'
      }
    }
  });

  module = function(app) {
    return app.load('../sample_data.csv', app.animate);
  };

  requirejs(["app"], module);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
