; var top1ByStateData = [{"state":"state name","region":"region"},
{"state":"Alabama","region":"South"},
{"state":"Alaska","region":"West"},
{"state":"Arizona","region":"West"},
{"state":"Arkansas","region":"South"},
{"state":"California","region":"West"},
{"state":"Colorado","region":"West"},
{"state":"Connecticut","region":"Northeast"},
{"state":"Delaware","region":"South"},
{"state":"District of Columbia","region":"South"},
{"state":"Florida","region":"South"},
{"state":"Georgia","region":"South"},
{"state":"Hawaii","region":"West"},
{"state":"Idaho","region":"West"},
{"state":"Illinois","region":"Midwest"},
{"state":"Indiana","region":"Midwest"},
{"state":"Iowa","region":"Midwest"},
{"state":"Kansas","region":"Midwest"},
{"state":"Kentucky","region":"South"},
{"state":"Louisiana","region":"South"},
{"state":"Maine","region":"Northeast"},
{"state":"Maryland","region":"South"},
{"state":"Massachusetts","region":"Northeast"},
{"state":"Michigan","region":"Midwest"},
{"state":"Midwest","region":""},
{"state":"Minnesota","region":"Midwest"},
{"state":"Mississippi","region":"South"},
{"state":"Missouri","region":"Midwest"},
{"state":"Montana","region":"West"},
{"state":"Nebraska","region":"Midwest"},
{"state":"Nevada","region":"West"},
{"state":"New Hampshire","region":"Northeast"},
{"state":"New Jersey","region":"Northeast"},
{"state":"New Mexico","region":"West"},
{"state":"New York","region":"Northeast"},
{"state":"North Carolina","region":"South"},
{"state":"North Dakota","region":"Midwest"},
{"state":"Northeast","region":""},
{"state":"Ohio","region":"Midwest"},
{"state":"Oklahoma","region":"South"},
{"state":"Oregon","region":"West"},
{"state":"Pennsylvania","region":"Northeast"},
{"state":"Rhode Island","region":"Northeast"},
{"state":"South","region":""},
{"state":"South Carolina","region":"South"},
{"state":"South Dakota","region":"Midwest"},
{"state":"Tennessee","region":"South"},
{"state":"Texas","region":"South"},
{"state":"United States","region":""},
{"state":"Utah","region":"West"},
{"state":"Vermont","region":"Northeast"},
{"state":"Virginia","region":"South"},
{"state":"Washington","region":"West"},
{"state":"West","region":""},
{"state":"West Virginia","region":"South"},
{"state":"Wisconsin","region":"Midwest"},
{"state":"Wyoming","region":"West"}];